import { expect, test, type Page, type TestInfo } from "@playwright/test";
import { mkdirSync, writeFileSync } from "node:fs";
import { A, B, C, TA, TB, navigationBrowser, switchLedger, activationRequests, fillEntry, deferred, row } from "./fixtures/p1-c-browser";
test.use({ video: "on" });
const heading = (page: Page) => page.getByTestId("surface-heading");
const detailHeading = (page: Page) => page.locator("[data-detail-heading]");
const status = (page: Page) => page.locator("[data-write-outcome]");
const dialog = (page: Page) => page.getByRole("dialog");
const homeURL = (id = A) => `/?v2Ledger=${id}`;
async function start(page: Page, path = "/") { const fixture = await navigationBrowser(page); await fixture.goto(path); await fixture.ready(); return fixture; }
async function home(page: Page, id = A) { await expect(page).toHaveURL(new RegExp(`\\?v2Ledger=${id}$`)); await expect(page.getByLabel("金額，新臺幣")).toBeVisible(); }
async function notSent(fixture: Awaited<ReturnType<typeof navigationBrowser>>, count: number) { await expect.poll(() => activationRequests(fixture.state).length).toBe(count); }
async function capture(page: Page, info: TestInfo, name: string, fixture?: Awaited<ReturnType<typeof navigationBrowser>>) { const directory = `output/playwright/p1-c/${info.project.name}`; mkdirSync(directory, { recursive: true }); await page.screenshot({ path: `${directory}/${name}.png`, fullPage: true }); if (fixture) writeFileSync(`${directory}/${name}-requests.json`, JSON.stringify(fixture.state.requests, null, 2)); }

test("01 normal launch replaces current URL with explicit canonical Ledger", async ({ page }) => { const length = await page.evaluate(() => history.length); await start(page); await home(page); expect(await page.evaluate(() => history.length)).toBe(length + 1); });
test("02 explicit B deep link reads only B", async ({ page }, info) => { const fixture = await start(page, homeURL(B)); await home(page, B); await expect(page.getByText("B 專屬車票", { exact: true })).toBeVisible(); expect(fixture.state.requests.filter(item => item.path.endsWith("/bootstrap")).map(item => item.path)).toEqual([`/api/app/v2/ledgers/${B}/bootstrap`]); await capture(page, info, "explicit-B", fixture); });
for (const [number, target] of [["03 nonexistent", "missing"], ["04 unauthorized", "00000000-0000-4000-8000-000000000099"]]) test(`${number} explicit target offers bounded recovery`, async ({ page }, info) => { const fixture = await navigationBrowser(page); await fixture.goto(homeURL(target)); await expect(page.getByText("這本帳本無法開啟，可能已失效或你沒有權限。", { exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "回自己的帳本" })).toBeVisible(); expect(fixture.state.requests.some(item => item.path.endsWith("/bootstrap"))).toBe(false); await capture(page, info, `invalid-${number.slice(0, 2)}`, fixture); await page.getByRole("button", { name: "回自己的帳本" }).click(); await home(page); });
test("05 invalid explicit B never paints A content", async ({ page }) => { const fixture = await navigationBrowser(page); await page.addInitScript(() => { const seen: string[] = []; Object.assign(window, { observedLedgerText: seen }); new MutationObserver(() => { if (document.body?.textContent?.includes("A 專屬晚餐")) seen.push("A"); }).observe(document, { childList: true, subtree: true, characterData: true }); }); await fixture.goto(homeURL("missing")); await expect(page.getByRole("button", { name: "回自己的帳本" })).toBeVisible(); expect(await page.evaluate(() => (window as unknown as { observedLedgerText: string[] }).observedLedgerText)).toEqual([]); expect(fixture.state.requests.filter(item => item.path.includes(`${A}/`))).toEqual([]); });
test("06 transaction with correct Ledger reconstructs and focuses detail", async ({ page }) => { const fixture = await navigationBrowser(page); await fixture.goto(`${homeURL(B)}&v2Transaction=${TB}`); await expect(page.getByRole("button", { name: "返回帳本", exact: true })).toBeVisible(); await expect(detailHeading(page)).toBeFocused(); await expect(page.getByText("B 專屬車票", { exact: true })).toBeVisible(); expect(fixture.state.requests.some(item => item.path.includes(`${A}/`))).toBe(false); });
test("07 transaction with wrong Ledger shows link error without guessing another Ledger", async ({ page }) => { const fixture = await navigationBrowser(page); await fixture.goto(`${homeURL(B)}&v2Transaction=${TA}`); await expect(page.getByText(/連結.*無法|紀錄.*無法|找不到.*紀錄/).first()).toBeVisible(); await expect(page.getByText("A 專屬晚餐", { exact: true })).toHaveCount(0); expect(fixture.state.requests.some(item => item.path.includes(`${A}/`))).toBe(false); });
test("08 transaction without Ledger does not scan for ownership", async ({ page }) => { const fixture = await navigationBrowser(page); await fixture.goto(`/?v2Transaction=${TA}`); await expect(page.getByText(/連結.*帳本|缺少.*帳本/).first()).toBeVisible(); expect(fixture.state.requests.filter(item => item.path.endsWith("/bootstrap"))).toEqual([]); expect(fixture.state.requests.some(item => item.path.includes(TA))).toBe(false); });
test("09 app row pushes detail and Back restores row focus", async ({ page }, info) => { await start(page); const origin = page.getByRole("button", { name: /A 專屬晚餐/ }); const count = await page.evaluate(() => history.length); await origin.click(); await expect(page).toHaveURL(new RegExp(`v2Transaction=${TA}`)); expect(await page.evaluate(() => history.length)).toBe(count + 1); await expect(detailHeading(page)).toBeFocused(); expect(JSON.stringify(await page.evaluate(() => history.state))).not.toContain("A 專屬晚餐"); await capture(page, info, "detail-app-origin"); await page.getByRole("button", { name: "返回帳本", exact: true }).click(); await home(page); await expect(origin).toBeFocused(); });
test("10 direct detail visible Back replaces to Home without leaving product", async ({ page }) => { const fixture = await navigationBrowser(page); await fixture.goto(`${homeURL(B)}&v2Transaction=${TB}`); await expect(page.getByRole("button", { name: "返回帳本", exact: true })).toBeVisible(); const count = await page.evaluate(() => history.length); await page.getByRole("button", { name: "返回帳本", exact: true }).click(); await home(page, B); expect(await page.evaluate(() => history.length)).toBe(count); });
test("11 reload detail preserves URL and drops stale app origin", async ({ page }) => { await start(page); await page.getByRole("button", { name: /A 專屬晚餐/ }).click(); await page.reload(); await expect(page).toHaveURL(new RegExp(`v2Transaction=${TA}`)); await expect(page.getByRole("button", { name: "返回帳本", exact: true })).toBeVisible(); await page.getByRole("button", { name: "返回帳本", exact: true }).click(); await home(page); });
for (const [number, label, tab] of [["12", "收支概況", "stats"], ["13", "帳本設定", "settings"]]) test(`${number} ${label} push reload deterministic Back`, async ({ page }, info) => { await start(page); const count = await page.evaluate(() => history.length); await page.getByRole("button", { name: label, exact: true }).click(); await expect(page).toHaveURL(new RegExp(`tab=${tab}`)); expect(await page.evaluate(() => history.length)).toBe(count + 1); await expect(heading(page)).toContainText(label); await expect(heading(page)).toBeFocused(); await capture(page, info, tab); await page.reload(); await expect(heading(page)).toContainText(label); await page.getByRole("button", { name: "返回帳本", exact: true }).click(); await home(page); });
test("14 recurring URL reconstructs secondary surface", async ({ page }) => { const fixture = await navigationBrowser(page); await fixture.goto(`${homeURL(B)}&tab=recurring`); await expect(heading(page)).toContainText(/固定記帳|週期/); await expect(page.getByRole("button", { name: "返回帳本", exact: true })).toBeVisible(); await page.getByRole("button", { name: "返回帳本", exact: true }).click(); await home(page, B); });
test("15 Search pushes URL and Back returns Home", async ({ page }) => { await start(page); const count = await page.evaluate(() => history.length); await page.getByRole("button", { name: "搜尋", exact: true }).click(); await expect(page).toHaveURL(/view=search/); expect(await page.evaluate(() => history.length)).toBe(count + 1); await expect(heading(page)).toBeFocused(); await page.getByLabel("搜尋紀錄").fill("A 專屬"); await expect(page.getByText("A 專屬晚餐", { exact: true })).toBeVisible(); await page.getByRole("button", { name: "返回帳本", exact: true }).click(); await home(page); });
test("16 manual A to B replaces Home and focuses accepted Ledger", async ({ page }) => { await start(page); const count = await page.evaluate(() => history.length); await switchLedger(page, B); await home(page, B); expect(await page.evaluate(() => history.length)).toBe(count); await expect(heading(page)).toBeFocused(); await expect(page.getByText("A 專屬晚餐", { exact: true })).toHaveCount(0); });
test("17 A to B to A is generation safe for queued preference", async ({ page }) => { const fixture = await start(page); const hold = deferred(); fixture.state.holdActivations.set(B, hold); await switchLedger(page, B); await home(page, B); await switchLedger(page, A); await home(page); hold.release(); await expect.poll(() => activationRequests(fixture.state).map(item => item.path)).toEqual([`/api/app/v2/ledgers/${B}/activate`, `/api/app/v2/ledgers/${A}/activate`]); await expect(page.getByText("A 專屬晚餐", { exact: true })).toBeVisible(); await expect(page.getByText("B 專屬車票", { exact: true })).toHaveCount(0); });
for (const [number, failure] of [["18", false], ["19", true]] as const) test(`${number} late A bootstrap ${failure ? "failure" : "success"} cannot update B`, async ({ page }) => { const fixture = await start(page), hold = deferred(); fixture.state.holdReads.set(A, hold); if (failure) fixture.state.failReads.set(A, 500); await page.getByLabel("重新整理帳本").click(); await expect.poll(() => fixture.state.requests.filter(item => item.path.endsWith(`${A}/bootstrap`)).length).toBe(2); await switchLedger(page, B); await home(page, B); hold.release(); await expect(page.getByText("B 專屬車票", { exact: true })).toBeVisible(); await expect(page.getByText(/共同生活 fixture read failure/)).toHaveCount(0); await expect(page.getByText("A 專屬晚餐", { exact: true })).toHaveCount(0); });
test("20 activation failure keeps B readable and retry touches preference only", async ({ page }, info) => { const fixture = await start(page); fixture.state.failActivations.add(B); await switchLedger(page, B); await home(page, B); await expect(page.getByText("這本可查看，LINE 的預設帳本尚未更新", { exact: false })).toBeVisible(); const reads = fixture.state.requests.filter(item => item.path.endsWith("/bootstrap")).length; fixture.state.failActivations.delete(B); await page.getByRole("button", { name: /重試.*預設|重新.*預設/ }).click(); await expect.poll(() => activationRequests(fixture.state).length).toBe(2); expect(fixture.state.requests.filter(item => item.path.endsWith("/bootstrap"))).toHaveLength(reads); await capture(page, info, "preference-retry", fixture); });
test("21 deep link B has NOT-SENT activate evidence", async ({ page }) => { const fixture = await start(page, homeURL(B)); await expect(page.getByText("B 專屬車票", { exact: true })).toBeVisible(); expect(activationRequests(fixture.state)).toEqual([]); });
test("22 explicit Switcher B sends preference activation once", async ({ page }) => { const fixture = await start(page); await switchLedger(page, B); await home(page, B); await expect.poll(() => activationRequests(fixture.state).length).toBe(1); expect(activationRequests(fixture.state)[0]!.path).toContain(B); });
test("23 initial draft switches without confirmation and receives fresh defaults", async ({ page }) => { await start(page); await switchLedger(page, B); await home(page, B); await expect(dialog(page)).toHaveCount(0); await expect(page.getByLabel("金額，新臺幣")).toHaveValue(""); });
test("24 amount-only dirty cancel preserves value focus URL and NOT-SENT activation", async ({ page }, info) => { const fixture = await start(page); const amount = page.getByLabel("金額，新臺幣"); await amount.fill("681"); await switchLedger(page, B); await expect(dialog(page)).toContainText("放棄這筆輸入，切換到『旅行』？"); await notSent(fixture, 0); await capture(page, info, "dirty-amount", fixture); await dialog(page).getByRole("button", { name: "繼續編輯", exact: true }).click(); await home(page); await expect(amount).toHaveValue("681"); await expect(amount).toBeFocused(); await notSent(fixture, 0); });
test("25 amount-only discard accepts B exactly once", async ({ page }) => { const fixture = await start(page); await page.getByLabel("金額，新臺幣").fill("681"); await switchLedger(page, B); await notSent(fixture, 0); await dialog(page).getByRole("button", { name: "放棄並切換", exact: true }).click(); await home(page, B); await expect(page.getByLabel("金額，新臺幣")).toHaveValue(""); await expect.poll(() => activationRequests(fixture.state).length).toBe(1); });
test("26 description dirty is guarded and semantic reversion becomes clean", async ({ page }) => { const fixture = await start(page); await page.getByLabel("用途", { exact: true }).fill("尚未完成"); await switchLedger(page, B); await notSent(fixture, 0); await dialog(page).getByRole("button", { name: "繼續編輯", exact: true }).click(); await page.getByLabel("用途", { exact: true }).fill(""); await switchLedger(page, B); await home(page, B); await expect(dialog(page)).toHaveCount(0); });
test("27 advanced-field-only note is dirty with empty amount and retains focus", async ({ page }) => { const fixture = await start(page); await page.getByText("更多", { exact: true }).click(); await page.getByLabel("備註").fill("保留進階值"); await switchLedger(page, B); await notSent(fixture, 0); await dialog(page).getByRole("button", { name: "繼續編輯", exact: true }).click(); await expect(page.getByLabel("備註")).toHaveValue("保留進階值"); await expect(page.getByLabel("備註")).toBeFocused(); await expect(page.getByLabel("金額，新臺幣")).toHaveValue(""); });
test("28 SUBMITTING blocks switch without aborting original POST", async ({ page }, info) => { const fixture = await start(page); fixture.state.mode = "delay"; await fillEntry(page); await page.getByRole("button", { name: "加入" }).click(); await expect.poll(() => fixture.state.posts.length).toBe(1); await switchLedger(page, B); await expect(dialog(page)).toContainText("這筆正在加入『共同生活』，完成後才能切換。"); await expect(dialog(page).getByRole("button", { name: "查看處理狀態" })).toBeVisible(); await notSent(fixture, 0); await capture(page, info, "submitting-blocked", fixture); fixture.state.postHold!.release(); await dialog(page).getByRole("button", { name: "查看處理狀態" }).click(); await expect(status(page)).toContainText("已加入晚餐"); await home(page); expect(fixture.state.posts).toHaveLength(1); });
for (const [number, failed] of [["29", false], ["30", true]] as const) test(`${number} COMMITTED with ${failed ? "failed" : "pending"} refresh permits switch`, async ({ page }) => { const fixture = await start(page); fixture.state.mode = "partial"; const hold = deferred(); if (failed) fixture.state.failReads.set(A, 500); else fixture.state.holdReads.set(A, hold); await fillEntry(page); await page.getByRole("button", { name: "加入" }).click(); await expect(status(page)).toContainText("已加入晚餐"); if (failed) await expect(status(page)).toContainText("其他紀錄暫時無法更新"); await switchLedger(page, B); await home(page, B); await expect(dialog(page)).toHaveCount(0); hold.release(); await expect(page.getByText("B 專屬車票", { exact: true })).toBeVisible(); expect(fixture.state.posts).toHaveLength(1); });
test("31 UNKNOWN blocks financial scope and activation is NOT-SENT", async ({ page }, info) => { const fixture = await start(page); fixture.state.mode = "drop"; await fillEntry(page); await page.getByRole("button", { name: "加入" }).click(); await expect(status(page)).toContainText("尚未確認是否已加入"); await switchLedger(page, B); await expect(dialog(page)).toContainText("這筆的結果還沒確認，請先確認，再切換帳本。"); await expect(dialog(page).getByRole("button", { name: "確認並完成這筆" })).toBeVisible(); await notSent(fixture, 0); expect(fixture.state.requests.some(item => item.path.includes(`${B}/`))).toBe(false); await capture(page, info, "unknown-blocked", fixture); });
test("32 UNKNOWN replay remains bound to original Ledger body and key", async ({ page }) => { const fixture = await start(page); fixture.state.mode = "drop"; await fillEntry(page); await page.getByRole("button", { name: "加入" }).click(); await expect(status(page)).toContainText("尚未確認是否已加入"); await switchLedger(page, B); await dialog(page).getByRole("button", { name: "確認並完成這筆" }).click(); await expect.poll(() => fixture.state.posts.length).toBe(2); expect(fixture.state.posts[1]).toEqual(fixture.state.posts[0]); expect(fixture.state.posts[1]!.endpoint).toContain(A); expect(fixture.state.effects).toBe(1); await notSent(fixture, 0); });
test("33 latest pending destination wins without queued switches", async ({ page }) => { const fixture = await start(page); await page.getByLabel("金額，新臺幣").fill("681"); await switchLedger(page, B); await page.getByRole("dialog").locator(`[data-ledger-option="${C}"]`).click(); await expect(dialog(page)).toContainText("家庭"); await notSent(fixture, 0); await dialog(page).getByRole("button", { name: /放棄並|放棄這筆輸入/ }).click(); await home(page, C); expect(fixture.state.requests.some(item => item.path.includes(`${B}/`))).toBe(false); });
for (const [number, accept] of [["34", false], ["35", true]] as const) test(`${number} popstate dirty ${accept ? "accept" : "cancel"} restores truth without activation`, async ({ page }) => { const fixture = await start(page, homeURL(B)); await page.evaluate(url => history.pushState({ externalKey: "keep" }, "", url), homeURL(A)); await home(page); await page.getByLabel("金額，新臺幣").fill("681"); await page.evaluate(() => history.back()); await expect(dialog(page)).toBeVisible(); await notSent(fixture, 0); await dialog(page).getByRole("button", { name: accept ? /放棄並|放棄這筆輸入/ : "繼續編輯" }).click(); await home(page, accept ? B : A); if (!accept) await expect(page.getByLabel("金額，新臺幣")).toHaveValue("681"); await notSent(fixture, 0); });
test("36 repeated Back and Forward do not loop or inflate history", async ({ page }) => { await start(page); await page.getByRole("button", { name: "收支概況", exact: true }).click(); const length = await page.evaluate(() => history.length); for (let index = 0; index < 3; index += 1) { await page.evaluate(() => history.back()); await home(page); await page.evaluate(() => history.forward()); await expect(page).toHaveURL(/tab=stats/); await expect(heading(page)).toContainText("收支概況"); } expect(await page.evaluate(() => history.length)).toBe(length); });
test("37 late activation and secondary errors cannot contaminate newer Ledger", async ({ page }) => { const fixture = await start(page), hold = deferred(), stats = deferred(); fixture.state.holdActivations.set(B, hold); fixture.state.failActivations.add(B); await switchLedger(page, B); await home(page, B); fixture.state.holdSecondary.set(`${B}/statistics`, stats); fixture.state.secondaryFailures.add(`${B}/statistics`); await page.getByRole("button", { name: "收支概況", exact: true }).click(); await expect.poll(() => fixture.state.requests.some(item => item.path.endsWith(`${B}/statistics`))).toBe(true); await switchLedger(page, A); await home(page); hold.release(); stats.release(); await expect.poll(() => fixture.state.defaultId).toBe(A); await expect(page.getByText(/preference fixture failure|stale 旅行|預設帳本尚未更新/)).toHaveCount(0); });
test("38 Escape equals visible cancel and host never stacks dialogs", async ({ page }) => { const fixture = await start(page); await page.getByLabel("金額，新臺幣").fill("681"); await switchLedger(page, B); await expect(page.locator("dialog[open]")).toHaveCount(1); await page.keyboard.press("Escape"); await expect(page.locator("dialog[open]")).toHaveCount(0); await home(page); await expect(page.getByLabel("金額，新臺幣")).toHaveValue("681"); await notSent(fixture, 0); });
test("39 native dialog labels traps background and restores Ledger trigger focus", async ({ page }, info) => { await start(page); const trigger = page.getByTestId("ledger-name-trigger"); await trigger.click(); await expect(dialog(page)).toHaveAccessibleName(/帳本/); await expect(page.locator("dialog[open]")).toHaveCount(1); await expect.poll(() => page.evaluate(() => Boolean(document.querySelector("dialog")?.contains(document.activeElement)))).toBe(true); await page.getByRole("button", { name: "收支概況", exact: true }).evaluate(element => (element as HTMLElement).focus()); expect(await page.evaluate(() => Boolean(document.querySelector("dialog")?.contains(document.activeElement)))).toBe(true); await capture(page, info, "native-switcher"); await page.keyboard.press("Escape"); await expect(trigger).toBeFocused(); await trigger.click(); await dialog(page).getByRole("button", { name: /關閉|取消/ }).first().click(); await expect(trigger).toBeFocused(); });
test("40 per-Ledger Home scroll restores A to B to A", async ({ page }, info) => { const fixture = await navigationBrowser(page); fixture.state.rows.push(...Array.from({ length: 35 }, (_, index) => row(A, `00000000-0000-4000-8000-${String(1000 + index).padStart(12, "0")}`, `A 滾動紀錄 ${index}`))); await fixture.goto(); await fixture.ready(); await page.getByRole("button", { name: /A 滾動紀錄 16/ }).scrollIntoViewIfNeeded(); const before = await page.evaluate(() => scrollY); expect(before).toBeGreaterThan(500); await page.getByTestId("ledger-name-trigger").evaluate(element => (element as HTMLElement).click()); await page.getByRole("dialog").locator(`[data-ledger-option="${B}"]`).click(); await home(page, B); await switchLedger(page, A); await home(page); await expect.poll(() => page.evaluate(() => scrollY)).toBeGreaterThan(before - 100); await expect.poll(() => page.evaluate(() => scrollY)).toBeLessThan(before + 100); expect(await page.evaluate(() => Object.keys(localStorage).some(key => /scroll/i.test(key)))).toBe(false); await capture(page, info, "scroll-restored"); });
test("41 Search query does not carry from A into B", async ({ page }) => { await start(page); await page.getByRole("button", { name: "搜尋", exact: true }).click(); await page.getByLabel("搜尋紀錄").fill("A 私人用途"); await switchLedger(page, B); await home(page, B); await page.getByRole("button", { name: "搜尋", exact: true }).click(); await expect(page.getByLabel("搜尋紀錄")).toHaveValue(""); expect(page.url()).not.toContain("私人"); });
test("42 proposal compatibility remains reachable without claimed Ledger ownership", async ({ page }) => { const fixture = await navigationBrowser(page); await fixture.goto("/?v2Proposal=fixture-proposal"); await expect(heading(page)).toContainText("LINE 待確認草稿"); await expect(page).toHaveURL(/v2Proposal=fixture-proposal/); expect(activationRequests(fixture.state)).toEqual([]); });
test("43 200 percent text has no body overflow and important controls remain 44px", async ({ page }, info) => { await start(page); await page.evaluate(() => { document.documentElement.style.fontSize = "200%"; }); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); for (const label of ["切換帳本", "收支概況", "帳本設定", "搜尋"]) { const box = await (label === "切換帳本" ? page.getByTestId("ledger-name-trigger") : page.getByRole("button", { name: label, exact: true })).boundingBox(); expect(box!.width).toBeGreaterThanOrEqual(44); expect(box!.height).toBeGreaterThanOrEqual(44); } await page.getByTestId("ledger-name-trigger").click(); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); await capture(page, info, "text-200-dialog"); });
test("44 reduced motion retains native focus and navigation", async ({ page }) => { await page.emulateMedia({ reducedMotion: "reduce" }); await start(page); await page.getByRole("button", { name: "帳本設定", exact: true }).click(); await expect(heading(page)).toBeFocused(); await page.getByRole("button", { name: "返回帳本", exact: true }).click(); await home(page); });

test("45 browser Back restores the original transaction row focus", async ({ page }) => {
  await start(page);
  const origin = page.getByRole("button", { name: /A 專屬晚餐/ });
  await origin.click(); await expect(detailHeading(page)).toBeFocused();
  await page.evaluate(() => history.back()); await home(page); await expect(origin).toBeFocused();
});

test("46 dirty discard into a secondary surface focuses heading after dialog closes", async ({ page }) => {
  await start(page); await page.getByLabel("金額，新臺幣").fill("681");
  await page.getByRole("button", { name: "收支概況", exact: true }).click();
  await dialog(page).getByRole("button", { name: "放棄這筆輸入", exact: true }).click();
  await expect(dialog(page)).toHaveCount(0); await expect(heading(page)).toBeFocused();
  await expect(page).toHaveURL(/tab=stats/);
});

test("47 amount and purpose closing guard cancels without losing input", async ({ page }) => {
  const fixture = await start(page); await fillEntry(page);
  await page.locator("[data-entry]").getByRole("button", { name: "取消", exact: true }).click();
  await expect(dialog(page)).toHaveAccessibleName("放棄這筆輸入？");
  await dialog(page).getByRole("button", { name: "繼續編輯" }).click();
  await expect(page.getByLabel("用途", { exact: true })).toHaveValue("晚餐");
  await expect(page.getByLabel("金額，新臺幣")).toHaveValue("681");
  expect(fixture.state.posts).toHaveLength(0);
});

test("48 UNKNOWN latest destination survives replay and replaces initial deep-link intent", async ({ page }) => {
  const fixture = await start(page); fixture.state.mode = "drop"; await fillEntry(page);
  await page.getByRole("button", { name: "加入" }).click(); await expect(status(page)).toContainText("尚未確認");
  await page.goto(homeURL(B)); await expect(status(page)).toContainText("尚未確認"); await expect(page).toHaveURL(new RegExp(`v2Ledger=${A}$`)); await expect(heading(page)).toHaveText("共同生活");
  await switchLedger(page, C); await dialog(page).getByRole("button", { name: "確認並完成這筆" }).click();
  await expect(status(page)).toContainText("已加入晚餐");
  await page.getByRole("button", { name: "繼續前往指定帳本" }).click(); await home(page, C);
  expect(fixture.state.posts).toHaveLength(2); expect(fixture.state.posts[1]).toEqual(fixture.state.posts[0]);
  expect(fixture.state.requests.some(item => item.path.includes(`${B}/`))).toBe(false);
  expect(activationRequests(fixture.state).every(item => item.path.includes(C))).toBe(true);
});

test("49 committed recovery awaiting A read permits B without hydrating A into B", async ({ page }) => {
  const fixture = await start(page); fixture.state.mode = "partial"; fixture.state.failReads.set(A, 500); await fillEntry(page);
  await page.getByRole("button", { name: "加入" }).click(); await expect(status(page)).toContainText("其他紀錄暫時無法更新");
  const hold = deferred(); fixture.state.holdReads.set(A, hold); fixture.state.failReads.delete(A);
  await page.reload(); await expect(heading(page)).toContainText("共同生活");
  await switchLedger(page, B); await home(page, B); hold.release();
  await expect(page.getByLabel("金額，新臺幣")).toBeEnabled();
  await expect(page.getByText(/已送出的操作與目前身分／帳本不符/)).toHaveCount(0);
  expect(fixture.state.posts).toHaveLength(1);
});

for (const code of [401, 403, 404, 500]) test(`50 bootstrap ${code} has a scoped recovery action`, async ({ page }) => {
  const fixture = await navigationBrowser(page); fixture.state.failReads.set(B, code); await fixture.goto(homeURL(B));
  await expect(page.getByRole("button", { name: code === 401 ? "重新登入" : code === 500 ? "重新讀取" : "回自己的帳本", exact: true })).toBeVisible();
  await expect(page.getByText("A 專屬晚餐", { exact: true })).toHaveCount(0);
  expect(fixture.state.requests.some(item => item.path.includes(`${A}/`))).toBe(false);
});
